# Generated by Django 5.0.7 on 2025-02-11 18:18

import django.db.models.deletion
import parler.fields
import parler.models
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/material')),
                ('tipo', models.CharField(choices=[('PELLET', 'PELLET'), ('FILAMENTO', 'FILAMENTO')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/soporte', verbose_name='Imagen')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='media/soporte/videos/', verbose_name='Video')),
                ('tipo_soporte', models.CharField(choices=[('Interfaz_Web', 'Interfaz_Web'), ('Simpify', 'Simpify'), ('Cabezal_DART', 'Cabezal_DART'), ('Cabezal_DD_HR', 'Cabezal_DD_HR'), ('Cabezal_Pellet', 'Cabezal_Pellet'), ('Mantenimiento', 'Mantenimiento'), ('Firmware', 'Firmware'), ('Manejo_de_impresoras', 'Manejo_de_impresoras'), ('Super_slicer', 'Super_slicer')], max_length=30, verbose_name='Tipo')),
                ('urlyoutube', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de video de YouTube')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/blog')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/avatar')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('summary', tinymce.models.HTMLField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.blog')),
            ],
            options={
                'verbose_name': 'blog Translation',
                'db_table': 'home_blog_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DuetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', tinymce.models.HTMLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.duet')),
            ],
            options={
                'verbose_name': 'duet Translation',
                'db_table': 'home_duet_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MaterialTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', tinymce.models.HTMLField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.material')),
            ],
            options={
                'verbose_name': 'material Translation',
                'db_table': 'home_material_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SoporteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.soporte')),
            ],
            options={
                'verbose_name': 'soporte Translation',
                'db_table': 'home_soporte_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
