# Generated by Django 5.0.7 on 2025-01-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/material')),
                ('summary', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('PELLET', 'PELLET'), ('FILAMENTO', 'FILAMENTO')], max_length=15)),
            ],
        ),
    ]
