# Generated by Django 5.0.7 on 2025-01-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images/Duet')),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
