# Generated by Django 5.0.7 on 2025-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_duet_alter_material_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/soporte', verbose_name='Imagen')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='media/soporte/videos/', verbose_name='Video')),
                ('tipo_soporte', models.CharField(choices=[('TECNICO', 'Técnico'), ('MANUAL Y CONFIGURACION', 'Manual y Configuración')], max_length=30, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
