# Generated by Django 5.0.7 on 2025-01-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='tipo_soporte',
            field=models.CharField(choices=[('Interaz Web', 'Interaz Web'), ('Simpify', 'Simpify'), ('Cabezal DART', 'Cabezal DART'), ('Cabezal DD HR', 'Cabezal DD HR'), ('Cabezal Pellet', 'Cabezal Pellet'), ('Mantenimiento', 'Mantenimiento'), ('Firmware', 'Firmware')], max_length=30, verbose_name='Tipo'),
        ),
    ]
