# Generated by Django 5.0.7 on 2025-01-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_soporte_tipo_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte',
            name='tipo_soporte',
            field=models.CharField(choices=[('Interfaz_Web', 'Interfaz_Web'), ('Simpify', 'Simpify'), ('Cabezal_DART', 'Cabezal_DART'), ('Cabezal_DD_HR', 'Cabezal_DD_HR'), ('Cabezal_Pellet', 'Cabezal_Pellet'), ('Mantenimiento', 'Mantenimiento'), ('Firmware', 'Firmware'), ('Manejo_de_impresoras', 'Manejo_de_impresoras'), ('Super_slicer', 'Super_slicer')], max_length=30, verbose_name='Tipo'),
        ),
    ]
