# Generated by Django 5.0.7 on 2025-01-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_soporte_tipo_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='elija_un_número'),
        ),
    ]
