# Generated by Django 5.0.7 on 2025-01-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_soporte_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte',
            name='urlyoutube',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de video de YouTube'),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='elija un número'),
        ),
    ]
