# Generated by Django 5.0.7 on 2025-02-03 08:22

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_soporte_urlyoutube_alter_soporte_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='duet',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='duet',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
