# Generated by Django 5.0.7 on 2025-02-03 15:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_duet_images_alter_duet_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duet',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soporte',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
    ]
