# Generated by Django 5.0.7 on 2025-02-04 10:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_blog_content_alter_blog_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=9999, null=True),
        ),
    ]
