# Generated by Django 5.0.7 on 2025-02-05 12:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
